### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by zh4ngx** [d2iq-archive/tachyon-mesos#5]
Currently running spark on mesos and interested in contributing to this, even though this was marked as 'just for fun.' Am I correct in saying that the best way to use tachyon with spark+mesos is to run it as a framework? If so, anything I can look at and possibly contribute to?

**Comment by xiaods** [comment]
I suggest setup tachyon-mesos in local environment first, then found the interesting point, then do your best.

**Comment by ohohoreilly** [comment]
@xiaods — that's some pretty good advice.
